# Generated by Django 5.2.8 on 2026-03-22 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suplidor', models.CharField(max_length=255)),
                ('rnc_suplidor', models.CharField(max_length=11)),
                ('num_factura', models.CharField(max_length=50)),
                ('ncf', models.CharField(max_length=13)),
                ('fecha_emision', models.DateField()),
                ('vencimiento_ncf', models.DateField(blank=True, null=True)),
                ('vencimiento_factura', models.DateField(blank=True, null=True)),
                ('itbis', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('archivo_original', models.ImageField(upload_to='facturas/%Y/%m/%d/')),
                ('procesada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
